# Site

title: Minis as Tokens
name: Frank Urbainsky
email: minisastokens.20.thedex@spamgourmet.com
description: >-
  If you want to use pictures of real minis as tokens in your online
  fantasy RPG campaing you have come to the right place!
domain: zuckerrausch.de  
url: https://minis.zuckerrausch.de # the base hostname & protocol for your site, e.g. http://example.com

logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
avatar: 'assets/images/sal.jpg'


include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-archives
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
      
# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 25

# category pages
jekyll-archives:
  enabled:
    - categories
  layouts:
    category: categories
  permalinks:
    category: '/category/:name/'

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules, Gemfile, Gemfile.lock, README.md, .gitignore]